sudo: required
services:
  - docker

before_install:
  - docker build -t geneiryodan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run geneiryodan/react-test npm test -- --coverage

after_success:
  - docker build -t geneiryodan/multi-client ./client
  - docker build -t geneiryodan/multi-nginx ./nginx
  - docker build -t geneiryodan/multi-server ./server
  - docker build -t geneiryodan/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push geneiryodan/multi-client
  - docker push geneiryodan/multi-nginx
  - docker push geneiryodan/multi-server
  - docker push geneiryodan/multi-worker
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-061554921305
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
